### PR TITLE
Switch lms-qa back to rolling deployments

### PR DESCRIPTION
**Pull request by robertknight**
Speed up our deployment process for lms on QA by switching to rolling
deploys. These change was at one point made manually but not committed
to the deployment repo. A recent change to the instance size then
unintentionally reset lms-qa to immutable deploys.

lms-qa and h-qa now use the same deployment settings, aside from
security group references, as shown by:

```
diff -u h/env-qa.yml lms/env-qa.yml
```

I also removed some commented-out configuration from the `h/env-qa.yaml` file.

### CODE REVIEW

**Comment by dmfine** [comment]
What we're doing in h-prod is the below - but not that I look at it I don't think that was captured in the config either :/   Sorry, I didn't understand how this worked back then. I'm making a note to make an issue to fix that. 

option_settings:
  aws:elasticbeanstalk:command:
    DeploymentPolicy: RollingWithAdditionalBatch
    BatchSizeType: Percentage
    BatchSize: 100

**Comment by robertknight** [comment]
@dmfine - Thanks for checking re h prod's config. Can you take care of that? In the meantime, are you happy for me to merge this PR with the changes for lms-qa?

**Comment by robertknight** [comment]
@dmfine - Ping. Can you take another look at this please when convenient?

**Comment by dmfine** [comment]
What I meant to communicate so long ago was that the way we do it here should match the way we do it in h-prod. 

> option_settings:
> aws:elasticbeanstalk:command:
> DeploymentPolicy: RollingWithAdditionalBatch
> BatchSizeType: Percentage
> BatchSize: 100

I edited it directly on the branch, please double check my work and then it's got my seal of approval to merge

**Comment by robertknight** [comment]
> I edited it directly on the branch, please double check my work and then it's got my seal of approval to merge

This confused me for a moment because this change, as explained in the description, was about making lms-qa work the same as h-qa. With the most recent commit `h/env-qa.yml` has now been changed (why?) and no longer matches `lms/env-qa.yml`.

My recollection is that the decision to use a different, faster deployment method for h-qa was an intentional choice some time ago. If you think we should reconsider then let's discuss - but I'd like to make that a separate change from what I was trying to do here which was speed up lms-qa deploys.

**Comment by robertknight** [comment]
I discussed this with @dmfine on the devops sync yesterday. It seems like there was a misunderstanding here. I have reverted this branch such that it only makes a functional change to the lms QA environment. The change to `h/env-qa.yml` is purely about removing commented-out configuration.

**Comment by robertknight** [comment]
Since this makes the same change that I've tested with Via recently, I'm going to go ahead and merge this and test with lms QA.

**Pull request merged**
